<?php


/**
 * This class defines the structure of the 'programacion_cancion' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * lun 13 dic 2010 20:45:42 COT
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class ProgramacionCancionTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.ProgramacionCancionTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('programacion_cancion');
		$this->setPhpName('ProgramacionCancion');
		$this->setClassname('ProgramacionCancion');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(false);
		// columns
		$this->addForeignPrimaryKey('CANCION', 'Cancion', 'INTEGER' , 'cancion', 'CODIGO', true, null, null);
		$this->addForeignPrimaryKey('VENTA', 'Venta', 'INTEGER' , 'venta', 'CODIGO', true, null, null);
		$this->addPrimaryKey('FECHA', 'Fecha', 'DATE', true, null, null);
		$this->addPrimaryKey('INICIO', 'Inicio', 'TIME', true, null, null);
		$this->addColumn('FIN', 'Fin', 'TIME', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('CancionRelatedByCancion', 'Cancion', RelationMap::MANY_TO_ONE, array('cancion' => 'codigo', ), null, null);
    $this->addRelation('VentaRelatedByVenta', 'Venta', RelationMap::MANY_TO_ONE, array('venta' => 'codigo', ), null, null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // ProgramacionCancionTableMap
