<?php


/**
 * This class defines the structure of the 'programacion_cuna' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * sáb 11 dic 2010 12:03:14 COT
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class ProgramacionCunaTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.ProgramacionCunaTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('programacion_cuna');
		$this->setPhpName('ProgramacionCuna');
		$this->setClassname('ProgramacionCuna');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(false);
		// columns
		$this->addPrimaryKey('VENTA', 'Venta', 'INTEGER', true, null, null);
		$this->addPrimaryKey('CUNIA_COMERCIAL', 'CuniaComercial', 'INTEGER', true, null, null);
		$this->addPrimaryKey('FECHA', 'Fecha', 'DATE', true, null, null);
		$this->addPrimaryKey('INICIO', 'Inicio', 'TIME', true, null, null);
		$this->addPrimaryKey('FIN', 'Fin', 'TIME', true, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // ProgramacionCunaTableMap
