<?php

/**
 * Base class that represents a row from the 'usuario' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Mon Dec 13 22:23:09 2010
 *
 * @package    lib.model.om
 */
abstract class BaseUsuario extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        UsuarioPeer
	 */
	protected static $peer;

	/**
	 * The value for the codigo field.
	 * @var        int
	 */
	protected $codigo;

	/**
	 * The value for the usuario field.
	 * @var        string
	 */
	protected $usuario;

	/**
	 * The value for the contrasena field.
	 * @var        string
	 */
	protected $contrasena;

	/**
	 * The value for the perfil field.
	 * @var        int
	 */
	protected $perfil;

	/**
	 * The value for the persona field.
	 * @var        int
	 */
	protected $persona;

	/**
	 * The value for the habilitado field.
	 * @var        boolean
	 */
	protected $habilitado;

	/**
	 * @var        Perfil
	 */
	protected $aPerfilRelatedByPerfil;

	/**
	 * @var        Persona
	 */
	protected $aPersonaRelatedByPersona;

	/**
	 * @var        array CuniaComercial[] Collection to store aggregation of CuniaComercial objects.
	 */
	protected $collCuniaComercials;

	/**
	 * @var        Criteria The criteria used to select the current contents of collCuniaComercials.
	 */
	private $lastCuniaComercialCriteria = null;

	/**
	 * @var        array Mensaje[] Collection to store aggregation of Mensaje objects.
	 */
	protected $collMensajes;

	/**
	 * @var        Criteria The criteria used to select the current contents of collMensajes.
	 */
	private $lastMensajeCriteria = null;

	/**
	 * @var        array Venta[] Collection to store aggregation of Venta objects.
	 */
	protected $collVentas;

	/**
	 * @var        Criteria The criteria used to select the current contents of collVentas.
	 */
	private $lastVentaCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'UsuarioPeer';

	/**
	 * Get the [codigo] column value.
	 * 
	 * @return     int
	 */
	public function getCodigo()
	{
		return $this->codigo;
	}

	/**
	 * Get the [usuario] column value.
	 * 
	 * @return     string
	 */
	public function getUsuario()
	{
		return $this->usuario;
	}

	/**
	 * Get the [contrasena] column value.
	 * 
	 * @return     string
	 */
	public function getContrasena()
	{
		return $this->contrasena;
	}

	/**
	 * Get the [perfil] column value.
	 * 
	 * @return     int
	 */
	public function getPerfil()
	{
		return $this->perfil;
	}

	/**
	 * Get the [persona] column value.
	 * 
	 * @return     int
	 */
	public function getPersona()
	{
		return $this->persona;
	}

	/**
	 * Get the [habilitado] column value.
	 * 
	 * @return     boolean
	 */
	public function getHabilitado()
	{
		return $this->habilitado;
	}

	/**
	 * Set the value of [codigo] column.
	 * 
	 * @param      int $v new value
	 * @return     Usuario The current object (for fluent API support)
	 */
	public function setCodigo($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->codigo !== $v) {
			$this->codigo = $v;
			$this->modifiedColumns[] = UsuarioPeer::CODIGO;
		}

		return $this;
	} // setCodigo()

	/**
	 * Set the value of [usuario] column.
	 * 
	 * @param      string $v new value
	 * @return     Usuario The current object (for fluent API support)
	 */
	public function setUsuario($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->usuario !== $v) {
			$this->usuario = $v;
			$this->modifiedColumns[] = UsuarioPeer::USUARIO;
		}

		return $this;
	} // setUsuario()

	/**
	 * Set the value of [contrasena] column.
	 * 
	 * @param      string $v new value
	 * @return     Usuario The current object (for fluent API support)
	 */
	public function setContrasena($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->contrasena !== $v) {
			$this->contrasena = $v;
			$this->modifiedColumns[] = UsuarioPeer::CONTRASENA;
		}

		return $this;
	} // setContrasena()

	/**
	 * Set the value of [perfil] column.
	 * 
	 * @param      int $v new value
	 * @return     Usuario The current object (for fluent API support)
	 */
	public function setPerfil($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->perfil !== $v) {
			$this->perfil = $v;
			$this->modifiedColumns[] = UsuarioPeer::PERFIL;
		}

		if ($this->aPerfilRelatedByPerfil !== null && $this->aPerfilRelatedByPerfil->getCodigo() !== $v) {
			$this->aPerfilRelatedByPerfil = null;
		}

		return $this;
	} // setPerfil()

	/**
	 * Set the value of [persona] column.
	 * 
	 * @param      int $v new value
	 * @return     Usuario The current object (for fluent API support)
	 */
	public function setPersona($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->persona !== $v) {
			$this->persona = $v;
			$this->modifiedColumns[] = UsuarioPeer::PERSONA;
		}

		if ($this->aPersonaRelatedByPersona !== null && $this->aPersonaRelatedByPersona->getCodigo() !== $v) {
			$this->aPersonaRelatedByPersona = null;
		}

		return $this;
	} // setPersona()

	/**
	 * Set the value of [habilitado] column.
	 * 
	 * @param      boolean $v new value
	 * @return     Usuario The current object (for fluent API support)
	 */
	public function setHabilitado($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->habilitado !== $v) {
			$this->habilitado = $v;
			$this->modifiedColumns[] = UsuarioPeer::HABILITADO;
		}

		return $this;
	} // setHabilitado()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->codigo = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->usuario = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->contrasena = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->perfil = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
			$this->persona = ($row[$startcol + 4] !== null) ? (int) $row[$startcol + 4] : null;
			$this->habilitado = ($row[$startcol + 5] !== null) ? (boolean) $row[$startcol + 5] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 6; // 6 = UsuarioPeer::NUM_COLUMNS - UsuarioPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Usuario object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aPerfilRelatedByPerfil !== null && $this->perfil !== $this->aPerfilRelatedByPerfil->getCodigo()) {
			$this->aPerfilRelatedByPerfil = null;
		}
		if ($this->aPersonaRelatedByPersona !== null && $this->persona !== $this->aPersonaRelatedByPersona->getCodigo()) {
			$this->aPersonaRelatedByPersona = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(UsuarioPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = UsuarioPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aPerfilRelatedByPerfil = null;
			$this->aPersonaRelatedByPersona = null;
			$this->collCuniaComercials = null;
			$this->lastCuniaComercialCriteria = null;

			$this->collMensajes = null;
			$this->lastMensajeCriteria = null;

			$this->collVentas = null;
			$this->lastVentaCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(UsuarioPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseUsuario:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				UsuarioPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseUsuario:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(UsuarioPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseUsuario:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseUsuario:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				UsuarioPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aPerfilRelatedByPerfil !== null) {
				if ($this->aPerfilRelatedByPerfil->isModified() || $this->aPerfilRelatedByPerfil->isNew()) {
					$affectedRows += $this->aPerfilRelatedByPerfil->save($con);
				}
				$this->setPerfilRelatedByPerfil($this->aPerfilRelatedByPerfil);
			}

			if ($this->aPersonaRelatedByPersona !== null) {
				if ($this->aPersonaRelatedByPersona->isModified() || $this->aPersonaRelatedByPersona->isNew()) {
					$affectedRows += $this->aPersonaRelatedByPersona->save($con);
				}
				$this->setPersonaRelatedByPersona($this->aPersonaRelatedByPersona);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = UsuarioPeer::CODIGO;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = UsuarioPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setCodigo($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += UsuarioPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collCuniaComercials !== null) {
				foreach ($this->collCuniaComercials as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collMensajes !== null) {
				foreach ($this->collMensajes as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collVentas !== null) {
				foreach ($this->collVentas as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aPerfilRelatedByPerfil !== null) {
				if (!$this->aPerfilRelatedByPerfil->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aPerfilRelatedByPerfil->getValidationFailures());
				}
			}

			if ($this->aPersonaRelatedByPersona !== null) {
				if (!$this->aPersonaRelatedByPersona->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aPersonaRelatedByPersona->getValidationFailures());
				}
			}


			if (($retval = UsuarioPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collCuniaComercials !== null) {
					foreach ($this->collCuniaComercials as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collMensajes !== null) {
					foreach ($this->collMensajes as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collVentas !== null) {
					foreach ($this->collVentas as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = UsuarioPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getCodigo();
				break;
			case 1:
				return $this->getUsuario();
				break;
			case 2:
				return $this->getContrasena();
				break;
			case 3:
				return $this->getPerfil();
				break;
			case 4:
				return $this->getPersona();
				break;
			case 5:
				return $this->getHabilitado();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = UsuarioPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getCodigo(),
			$keys[1] => $this->getUsuario(),
			$keys[2] => $this->getContrasena(),
			$keys[3] => $this->getPerfil(),
			$keys[4] => $this->getPersona(),
			$keys[5] => $this->getHabilitado(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = UsuarioPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setCodigo($value);
				break;
			case 1:
				$this->setUsuario($value);
				break;
			case 2:
				$this->setContrasena($value);
				break;
			case 3:
				$this->setPerfil($value);
				break;
			case 4:
				$this->setPersona($value);
				break;
			case 5:
				$this->setHabilitado($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = UsuarioPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setCodigo($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setUsuario($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setContrasena($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setPerfil($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setPersona($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setHabilitado($arr[$keys[5]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(UsuarioPeer::DATABASE_NAME);

		if ($this->isColumnModified(UsuarioPeer::CODIGO)) $criteria->add(UsuarioPeer::CODIGO, $this->codigo);
		if ($this->isColumnModified(UsuarioPeer::USUARIO)) $criteria->add(UsuarioPeer::USUARIO, $this->usuario);
		if ($this->isColumnModified(UsuarioPeer::CONTRASENA)) $criteria->add(UsuarioPeer::CONTRASENA, $this->contrasena);
		if ($this->isColumnModified(UsuarioPeer::PERFIL)) $criteria->add(UsuarioPeer::PERFIL, $this->perfil);
		if ($this->isColumnModified(UsuarioPeer::PERSONA)) $criteria->add(UsuarioPeer::PERSONA, $this->persona);
		if ($this->isColumnModified(UsuarioPeer::HABILITADO)) $criteria->add(UsuarioPeer::HABILITADO, $this->habilitado);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(UsuarioPeer::DATABASE_NAME);

		$criteria->add(UsuarioPeer::CODIGO, $this->codigo);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getCodigo();
	}

	/**
	 * Generic method to set the primary key (codigo column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setCodigo($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Usuario (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setUsuario($this->usuario);

		$copyObj->setContrasena($this->contrasena);

		$copyObj->setPerfil($this->perfil);

		$copyObj->setPersona($this->persona);

		$copyObj->setHabilitado($this->habilitado);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getCuniaComercials() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addCuniaComercial($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getMensajes() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addMensaje($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getVentas() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addVenta($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setCodigo(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Usuario Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     UsuarioPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new UsuarioPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Perfil object.
	 *
	 * @param      Perfil $v
	 * @return     Usuario The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setPerfilRelatedByPerfil(Perfil $v = null)
	{
		if ($v === null) {
			$this->setPerfil(NULL);
		} else {
			$this->setPerfil($v->getCodigo());
		}

		$this->aPerfilRelatedByPerfil = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Perfil object, it will not be re-added.
		if ($v !== null) {
			$v->addUsuario($this);
		}

		return $this;
	}


	/**
	 * Get the associated Perfil object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Perfil The associated Perfil object.
	 * @throws     PropelException
	 */
	public function getPerfilRelatedByPerfil(PropelPDO $con = null)
	{
		if ($this->aPerfilRelatedByPerfil === null && ($this->perfil !== null)) {
			$this->aPerfilRelatedByPerfil = PerfilPeer::retrieveByPk($this->perfil);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aPerfilRelatedByPerfil->addUsuarios($this);
			 */
		}
		return $this->aPerfilRelatedByPerfil;
	}

	/**
	 * Declares an association between this object and a Persona object.
	 *
	 * @param      Persona $v
	 * @return     Usuario The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setPersonaRelatedByPersona(Persona $v = null)
	{
		if ($v === null) {
			$this->setPersona(NULL);
		} else {
			$this->setPersona($v->getCodigo());
		}

		$this->aPersonaRelatedByPersona = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Persona object, it will not be re-added.
		if ($v !== null) {
			$v->addUsuario($this);
		}

		return $this;
	}


	/**
	 * Get the associated Persona object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Persona The associated Persona object.
	 * @throws     PropelException
	 */
	public function getPersonaRelatedByPersona(PropelPDO $con = null)
	{
		if ($this->aPersonaRelatedByPersona === null && ($this->persona !== null)) {
			$this->aPersonaRelatedByPersona = PersonaPeer::retrieveByPk($this->persona);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aPersonaRelatedByPersona->addUsuarios($this);
			 */
		}
		return $this->aPersonaRelatedByPersona;
	}

	/**
	 * Clears out the collCuniaComercials collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addCuniaComercials()
	 */
	public function clearCuniaComercials()
	{
		$this->collCuniaComercials = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collCuniaComercials collection (array).
	 *
	 * By default this just sets the collCuniaComercials collection to an empty array (like clearcollCuniaComercials());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initCuniaComercials()
	{
		$this->collCuniaComercials = array();
	}

	/**
	 * Gets an array of CuniaComercial objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Usuario has previously been saved, it will retrieve
	 * related CuniaComercials from storage. If this Usuario is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array CuniaComercial[]
	 * @throws     PropelException
	 */
	public function getCuniaComercials($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UsuarioPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collCuniaComercials === null) {
			if ($this->isNew()) {
			   $this->collCuniaComercials = array();
			} else {

				$criteria->add(CuniaComercialPeer::USUARIO, $this->codigo);

				CuniaComercialPeer::addSelectColumns($criteria);
				$this->collCuniaComercials = CuniaComercialPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(CuniaComercialPeer::USUARIO, $this->codigo);

				CuniaComercialPeer::addSelectColumns($criteria);
				if (!isset($this->lastCuniaComercialCriteria) || !$this->lastCuniaComercialCriteria->equals($criteria)) {
					$this->collCuniaComercials = CuniaComercialPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastCuniaComercialCriteria = $criteria;
		return $this->collCuniaComercials;
	}

	/**
	 * Returns the number of related CuniaComercial objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related CuniaComercial objects.
	 * @throws     PropelException
	 */
	public function countCuniaComercials(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UsuarioPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collCuniaComercials === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(CuniaComercialPeer::USUARIO, $this->codigo);

				$count = CuniaComercialPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(CuniaComercialPeer::USUARIO, $this->codigo);

				if (!isset($this->lastCuniaComercialCriteria) || !$this->lastCuniaComercialCriteria->equals($criteria)) {
					$count = CuniaComercialPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collCuniaComercials);
				}
			} else {
				$count = count($this->collCuniaComercials);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a CuniaComercial object to this object
	 * through the CuniaComercial foreign key attribute.
	 *
	 * @param      CuniaComercial $l CuniaComercial
	 * @return     void
	 * @throws     PropelException
	 */
	public function addCuniaComercial(CuniaComercial $l)
	{
		if ($this->collCuniaComercials === null) {
			$this->initCuniaComercials();
		}
		if (!in_array($l, $this->collCuniaComercials, true)) { // only add it if the **same** object is not already associated
			array_push($this->collCuniaComercials, $l);
			$l->setUsuarioRelatedByUsuario($this);
		}
	}

	/**
	 * Clears out the collMensajes collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addMensajes()
	 */
	public function clearMensajes()
	{
		$this->collMensajes = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collMensajes collection (array).
	 *
	 * By default this just sets the collMensajes collection to an empty array (like clearcollMensajes());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initMensajes()
	{
		$this->collMensajes = array();
	}

	/**
	 * Gets an array of Mensaje objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Usuario has previously been saved, it will retrieve
	 * related Mensajes from storage. If this Usuario is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Mensaje[]
	 * @throws     PropelException
	 */
	public function getMensajes($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UsuarioPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collMensajes === null) {
			if ($this->isNew()) {
			   $this->collMensajes = array();
			} else {

				$criteria->add(MensajePeer::USUARIO, $this->codigo);

				MensajePeer::addSelectColumns($criteria);
				$this->collMensajes = MensajePeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(MensajePeer::USUARIO, $this->codigo);

				MensajePeer::addSelectColumns($criteria);
				if (!isset($this->lastMensajeCriteria) || !$this->lastMensajeCriteria->equals($criteria)) {
					$this->collMensajes = MensajePeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastMensajeCriteria = $criteria;
		return $this->collMensajes;
	}

	/**
	 * Returns the number of related Mensaje objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Mensaje objects.
	 * @throws     PropelException
	 */
	public function countMensajes(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UsuarioPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collMensajes === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(MensajePeer::USUARIO, $this->codigo);

				$count = MensajePeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(MensajePeer::USUARIO, $this->codigo);

				if (!isset($this->lastMensajeCriteria) || !$this->lastMensajeCriteria->equals($criteria)) {
					$count = MensajePeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collMensajes);
				}
			} else {
				$count = count($this->collMensajes);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Mensaje object to this object
	 * through the Mensaje foreign key attribute.
	 *
	 * @param      Mensaje $l Mensaje
	 * @return     void
	 * @throws     PropelException
	 */
	public function addMensaje(Mensaje $l)
	{
		if ($this->collMensajes === null) {
			$this->initMensajes();
		}
		if (!in_array($l, $this->collMensajes, true)) { // only add it if the **same** object is not already associated
			array_push($this->collMensajes, $l);
			$l->setUsuarioRelatedByUsuario($this);
		}
	}

	/**
	 * Clears out the collVentas collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addVentas()
	 */
	public function clearVentas()
	{
		$this->collVentas = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collVentas collection (array).
	 *
	 * By default this just sets the collVentas collection to an empty array (like clearcollVentas());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initVentas()
	{
		$this->collVentas = array();
	}

	/**
	 * Gets an array of Venta objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Usuario has previously been saved, it will retrieve
	 * related Ventas from storage. If this Usuario is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Venta[]
	 * @throws     PropelException
	 */
	public function getVentas($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UsuarioPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collVentas === null) {
			if ($this->isNew()) {
			   $this->collVentas = array();
			} else {

				$criteria->add(VentaPeer::USUARIO, $this->codigo);

				VentaPeer::addSelectColumns($criteria);
				$this->collVentas = VentaPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(VentaPeer::USUARIO, $this->codigo);

				VentaPeer::addSelectColumns($criteria);
				if (!isset($this->lastVentaCriteria) || !$this->lastVentaCriteria->equals($criteria)) {
					$this->collVentas = VentaPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastVentaCriteria = $criteria;
		return $this->collVentas;
	}

	/**
	 * Returns the number of related Venta objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Venta objects.
	 * @throws     PropelException
	 */
	public function countVentas(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UsuarioPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collVentas === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(VentaPeer::USUARIO, $this->codigo);

				$count = VentaPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(VentaPeer::USUARIO, $this->codigo);

				if (!isset($this->lastVentaCriteria) || !$this->lastVentaCriteria->equals($criteria)) {
					$count = VentaPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collVentas);
				}
			} else {
				$count = count($this->collVentas);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Venta object to this object
	 * through the Venta foreign key attribute.
	 *
	 * @param      Venta $l Venta
	 * @return     void
	 * @throws     PropelException
	 */
	public function addVenta(Venta $l)
	{
		if ($this->collVentas === null) {
			$this->initVentas();
		}
		if (!in_array($l, $this->collVentas, true)) { // only add it if the **same** object is not already associated
			array_push($this->collVentas, $l);
			$l->setUsuarioRelatedByUsuario($this);
		}
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collCuniaComercials) {
				foreach ((array) $this->collCuniaComercials as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collMensajes) {
				foreach ((array) $this->collMensajes as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collVentas) {
				foreach ((array) $this->collVentas as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collCuniaComercials = null;
		$this->collMensajes = null;
		$this->collVentas = null;
			$this->aPerfilRelatedByPerfil = null;
			$this->aPersonaRelatedByPersona = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseUsuario:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseUsuario::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseUsuario
