<?php

/**
 * Base class that represents a row from the 'venta' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * lun 13 dic 2010 20:45:43 COT
 *
 * @package    lib.model.om
 */
abstract class BaseVenta extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        VentaPeer
	 */
	protected static $peer;

	/**
	 * The value for the codigo field.
	 * @var        int
	 */
	protected $codigo;

	/**
	 * The value for the usuario field.
	 * @var        int
	 */
	protected $usuario;

	/**
	 * The value for the precio field.
	 * @var        string
	 */
	protected $precio;

	/**
	 * The value for the fecha_venta field.
	 * @var        string
	 */
	protected $fecha_venta;

	/**
	 * @var        Usuario
	 */
	protected $aUsuarioRelatedByUsuario;

	/**
	 * @var        array ProgramacionCancion[] Collection to store aggregation of ProgramacionCancion objects.
	 */
	protected $collProgramacionCancions;

	/**
	 * @var        Criteria The criteria used to select the current contents of collProgramacionCancions.
	 */
	private $lastProgramacionCancionCriteria = null;

	/**
	 * @var        array VentaCancion[] Collection to store aggregation of VentaCancion objects.
	 */
	protected $collVentaCancions;

	/**
	 * @var        Criteria The criteria used to select the current contents of collVentaCancions.
	 */
	private $lastVentaCancionCriteria = null;

	/**
	 * @var        array VentaCuniaComercial[] Collection to store aggregation of VentaCuniaComercial objects.
	 */
	protected $collVentaCuniaComercials;

	/**
	 * @var        Criteria The criteria used to select the current contents of collVentaCuniaComercials.
	 */
	private $lastVentaCuniaComercialCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'VentaPeer';

	/**
	 * Get the [codigo] column value.
	 * 
	 * @return     int
	 */
	public function getCodigo()
	{
		return $this->codigo;
	}

	/**
	 * Get the [usuario] column value.
	 * 
	 * @return     int
	 */
	public function getUsuario()
	{
		return $this->usuario;
	}

	/**
	 * Get the [precio] column value.
	 * 
	 * @return     string
	 */
	public function getPrecio()
	{
		return $this->precio;
	}

	/**
	 * Get the [optionally formatted] temporal [fecha_venta] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getFechaVenta($format = 'Y-m-d H:i:s')
	{
		if ($this->fecha_venta === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->fecha_venta);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->fecha_venta, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Set the value of [codigo] column.
	 * 
	 * @param      int $v new value
	 * @return     Venta The current object (for fluent API support)
	 */
	public function setCodigo($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->codigo !== $v) {
			$this->codigo = $v;
			$this->modifiedColumns[] = VentaPeer::CODIGO;
		}

		return $this;
	} // setCodigo()

	/**
	 * Set the value of [usuario] column.
	 * 
	 * @param      int $v new value
	 * @return     Venta The current object (for fluent API support)
	 */
	public function setUsuario($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->usuario !== $v) {
			$this->usuario = $v;
			$this->modifiedColumns[] = VentaPeer::USUARIO;
		}

		if ($this->aUsuarioRelatedByUsuario !== null && $this->aUsuarioRelatedByUsuario->getCodigo() !== $v) {
			$this->aUsuarioRelatedByUsuario = null;
		}

		return $this;
	} // setUsuario()

	/**
	 * Set the value of [precio] column.
	 * 
	 * @param      string $v new value
	 * @return     Venta The current object (for fluent API support)
	 */
	public function setPrecio($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->precio !== $v) {
			$this->precio = $v;
			$this->modifiedColumns[] = VentaPeer::PRECIO;
		}

		return $this;
	} // setPrecio()

	/**
	 * Sets the value of [fecha_venta] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Venta The current object (for fluent API support)
	 */
	public function setFechaVenta($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->fecha_venta !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->fecha_venta !== null && $tmpDt = new DateTime($this->fecha_venta)) ? $tmpDt->format('Y-m-d\\TH:i:sO') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d\\TH:i:sO') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->fecha_venta = ($dt ? $dt->format('Y-m-d\\TH:i:sO') : null);
				$this->modifiedColumns[] = VentaPeer::FECHA_VENTA;
			}
		} // if either are not null

		return $this;
	} // setFechaVenta()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->codigo = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->usuario = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->precio = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->fecha_venta = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 4; // 4 = VentaPeer::NUM_COLUMNS - VentaPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Venta object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aUsuarioRelatedByUsuario !== null && $this->usuario !== $this->aUsuarioRelatedByUsuario->getCodigo()) {
			$this->aUsuarioRelatedByUsuario = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(VentaPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = VentaPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aUsuarioRelatedByUsuario = null;
			$this->collProgramacionCancions = null;
			$this->lastProgramacionCancionCriteria = null;

			$this->collVentaCancions = null;
			$this->lastVentaCancionCriteria = null;

			$this->collVentaCuniaComercials = null;
			$this->lastVentaCuniaComercialCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(VentaPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseVenta:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				VentaPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseVenta:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(VentaPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseVenta:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseVenta:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				VentaPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aUsuarioRelatedByUsuario !== null) {
				if ($this->aUsuarioRelatedByUsuario->isModified() || $this->aUsuarioRelatedByUsuario->isNew()) {
					$affectedRows += $this->aUsuarioRelatedByUsuario->save($con);
				}
				$this->setUsuarioRelatedByUsuario($this->aUsuarioRelatedByUsuario);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = VentaPeer::CODIGO;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = VentaPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setCodigo($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += VentaPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collProgramacionCancions !== null) {
				foreach ($this->collProgramacionCancions as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collVentaCancions !== null) {
				foreach ($this->collVentaCancions as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collVentaCuniaComercials !== null) {
				foreach ($this->collVentaCuniaComercials as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aUsuarioRelatedByUsuario !== null) {
				if (!$this->aUsuarioRelatedByUsuario->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aUsuarioRelatedByUsuario->getValidationFailures());
				}
			}


			if (($retval = VentaPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collProgramacionCancions !== null) {
					foreach ($this->collProgramacionCancions as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collVentaCancions !== null) {
					foreach ($this->collVentaCancions as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collVentaCuniaComercials !== null) {
					foreach ($this->collVentaCuniaComercials as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = VentaPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getCodigo();
				break;
			case 1:
				return $this->getUsuario();
				break;
			case 2:
				return $this->getPrecio();
				break;
			case 3:
				return $this->getFechaVenta();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = VentaPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getCodigo(),
			$keys[1] => $this->getUsuario(),
			$keys[2] => $this->getPrecio(),
			$keys[3] => $this->getFechaVenta(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = VentaPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setCodigo($value);
				break;
			case 1:
				$this->setUsuario($value);
				break;
			case 2:
				$this->setPrecio($value);
				break;
			case 3:
				$this->setFechaVenta($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = VentaPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setCodigo($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setUsuario($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setPrecio($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setFechaVenta($arr[$keys[3]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(VentaPeer::DATABASE_NAME);

		if ($this->isColumnModified(VentaPeer::CODIGO)) $criteria->add(VentaPeer::CODIGO, $this->codigo);
		if ($this->isColumnModified(VentaPeer::USUARIO)) $criteria->add(VentaPeer::USUARIO, $this->usuario);
		if ($this->isColumnModified(VentaPeer::PRECIO)) $criteria->add(VentaPeer::PRECIO, $this->precio);
		if ($this->isColumnModified(VentaPeer::FECHA_VENTA)) $criteria->add(VentaPeer::FECHA_VENTA, $this->fecha_venta);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(VentaPeer::DATABASE_NAME);

		$criteria->add(VentaPeer::CODIGO, $this->codigo);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getCodigo();
	}

	/**
	 * Generic method to set the primary key (codigo column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setCodigo($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Venta (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setUsuario($this->usuario);

		$copyObj->setPrecio($this->precio);

		$copyObj->setFechaVenta($this->fecha_venta);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getProgramacionCancions() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addProgramacionCancion($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getVentaCancions() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addVentaCancion($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getVentaCuniaComercials() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addVentaCuniaComercial($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setCodigo(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Venta Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     VentaPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new VentaPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Usuario object.
	 *
	 * @param      Usuario $v
	 * @return     Venta The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setUsuarioRelatedByUsuario(Usuario $v = null)
	{
		if ($v === null) {
			$this->setUsuario(NULL);
		} else {
			$this->setUsuario($v->getCodigo());
		}

		$this->aUsuarioRelatedByUsuario = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Usuario object, it will not be re-added.
		if ($v !== null) {
			$v->addVenta($this);
		}

		return $this;
	}


	/**
	 * Get the associated Usuario object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Usuario The associated Usuario object.
	 * @throws     PropelException
	 */
	public function getUsuarioRelatedByUsuario(PropelPDO $con = null)
	{
		if ($this->aUsuarioRelatedByUsuario === null && ($this->usuario !== null)) {
			$this->aUsuarioRelatedByUsuario = UsuarioPeer::retrieveByPk($this->usuario);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aUsuarioRelatedByUsuario->addVentas($this);
			 */
		}
		return $this->aUsuarioRelatedByUsuario;
	}

	/**
	 * Clears out the collProgramacionCancions collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addProgramacionCancions()
	 */
	public function clearProgramacionCancions()
	{
		$this->collProgramacionCancions = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collProgramacionCancions collection (array).
	 *
	 * By default this just sets the collProgramacionCancions collection to an empty array (like clearcollProgramacionCancions());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initProgramacionCancions()
	{
		$this->collProgramacionCancions = array();
	}

	/**
	 * Gets an array of ProgramacionCancion objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Venta has previously been saved, it will retrieve
	 * related ProgramacionCancions from storage. If this Venta is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array ProgramacionCancion[]
	 * @throws     PropelException
	 */
	public function getProgramacionCancions($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(VentaPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collProgramacionCancions === null) {
			if ($this->isNew()) {
			   $this->collProgramacionCancions = array();
			} else {

				$criteria->add(ProgramacionCancionPeer::VENTA, $this->codigo);

				ProgramacionCancionPeer::addSelectColumns($criteria);
				$this->collProgramacionCancions = ProgramacionCancionPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(ProgramacionCancionPeer::VENTA, $this->codigo);

				ProgramacionCancionPeer::addSelectColumns($criteria);
				if (!isset($this->lastProgramacionCancionCriteria) || !$this->lastProgramacionCancionCriteria->equals($criteria)) {
					$this->collProgramacionCancions = ProgramacionCancionPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastProgramacionCancionCriteria = $criteria;
		return $this->collProgramacionCancions;
	}

	/**
	 * Returns the number of related ProgramacionCancion objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related ProgramacionCancion objects.
	 * @throws     PropelException
	 */
	public function countProgramacionCancions(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(VentaPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collProgramacionCancions === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(ProgramacionCancionPeer::VENTA, $this->codigo);

				$count = ProgramacionCancionPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(ProgramacionCancionPeer::VENTA, $this->codigo);

				if (!isset($this->lastProgramacionCancionCriteria) || !$this->lastProgramacionCancionCriteria->equals($criteria)) {
					$count = ProgramacionCancionPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collProgramacionCancions);
				}
			} else {
				$count = count($this->collProgramacionCancions);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a ProgramacionCancion object to this object
	 * through the ProgramacionCancion foreign key attribute.
	 *
	 * @param      ProgramacionCancion $l ProgramacionCancion
	 * @return     void
	 * @throws     PropelException
	 */
	public function addProgramacionCancion(ProgramacionCancion $l)
	{
		if ($this->collProgramacionCancions === null) {
			$this->initProgramacionCancions();
		}
		if (!in_array($l, $this->collProgramacionCancions, true)) { // only add it if the **same** object is not already associated
			array_push($this->collProgramacionCancions, $l);
			$l->setVentaRelatedByVenta($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Venta is new, it will return
	 * an empty collection; or if this Venta has previously
	 * been saved, it will retrieve related ProgramacionCancions from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Venta.
	 */
	public function getProgramacionCancionsJoinCancionRelatedByCancion($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(VentaPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collProgramacionCancions === null) {
			if ($this->isNew()) {
				$this->collProgramacionCancions = array();
			} else {

				$criteria->add(ProgramacionCancionPeer::VENTA, $this->codigo);

				$this->collProgramacionCancions = ProgramacionCancionPeer::doSelectJoinCancionRelatedByCancion($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(ProgramacionCancionPeer::VENTA, $this->codigo);

			if (!isset($this->lastProgramacionCancionCriteria) || !$this->lastProgramacionCancionCriteria->equals($criteria)) {
				$this->collProgramacionCancions = ProgramacionCancionPeer::doSelectJoinCancionRelatedByCancion($criteria, $con, $join_behavior);
			}
		}
		$this->lastProgramacionCancionCriteria = $criteria;

		return $this->collProgramacionCancions;
	}

	/**
	 * Clears out the collVentaCancions collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addVentaCancions()
	 */
	public function clearVentaCancions()
	{
		$this->collVentaCancions = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collVentaCancions collection (array).
	 *
	 * By default this just sets the collVentaCancions collection to an empty array (like clearcollVentaCancions());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initVentaCancions()
	{
		$this->collVentaCancions = array();
	}

	/**
	 * Gets an array of VentaCancion objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Venta has previously been saved, it will retrieve
	 * related VentaCancions from storage. If this Venta is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array VentaCancion[]
	 * @throws     PropelException
	 */
	public function getVentaCancions($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(VentaPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collVentaCancions === null) {
			if ($this->isNew()) {
			   $this->collVentaCancions = array();
			} else {

				$criteria->add(VentaCancionPeer::VENTA, $this->codigo);

				VentaCancionPeer::addSelectColumns($criteria);
				$this->collVentaCancions = VentaCancionPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(VentaCancionPeer::VENTA, $this->codigo);

				VentaCancionPeer::addSelectColumns($criteria);
				if (!isset($this->lastVentaCancionCriteria) || !$this->lastVentaCancionCriteria->equals($criteria)) {
					$this->collVentaCancions = VentaCancionPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastVentaCancionCriteria = $criteria;
		return $this->collVentaCancions;
	}

	/**
	 * Returns the number of related VentaCancion objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related VentaCancion objects.
	 * @throws     PropelException
	 */
	public function countVentaCancions(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(VentaPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collVentaCancions === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(VentaCancionPeer::VENTA, $this->codigo);

				$count = VentaCancionPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(VentaCancionPeer::VENTA, $this->codigo);

				if (!isset($this->lastVentaCancionCriteria) || !$this->lastVentaCancionCriteria->equals($criteria)) {
					$count = VentaCancionPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collVentaCancions);
				}
			} else {
				$count = count($this->collVentaCancions);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a VentaCancion object to this object
	 * through the VentaCancion foreign key attribute.
	 *
	 * @param      VentaCancion $l VentaCancion
	 * @return     void
	 * @throws     PropelException
	 */
	public function addVentaCancion(VentaCancion $l)
	{
		if ($this->collVentaCancions === null) {
			$this->initVentaCancions();
		}
		if (!in_array($l, $this->collVentaCancions, true)) { // only add it if the **same** object is not already associated
			array_push($this->collVentaCancions, $l);
			$l->setVentaRelatedByVenta($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Venta is new, it will return
	 * an empty collection; or if this Venta has previously
	 * been saved, it will retrieve related VentaCancions from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Venta.
	 */
	public function getVentaCancionsJoinCancionRelatedByCancion($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(VentaPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collVentaCancions === null) {
			if ($this->isNew()) {
				$this->collVentaCancions = array();
			} else {

				$criteria->add(VentaCancionPeer::VENTA, $this->codigo);

				$this->collVentaCancions = VentaCancionPeer::doSelectJoinCancionRelatedByCancion($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(VentaCancionPeer::VENTA, $this->codigo);

			if (!isset($this->lastVentaCancionCriteria) || !$this->lastVentaCancionCriteria->equals($criteria)) {
				$this->collVentaCancions = VentaCancionPeer::doSelectJoinCancionRelatedByCancion($criteria, $con, $join_behavior);
			}
		}
		$this->lastVentaCancionCriteria = $criteria;

		return $this->collVentaCancions;
	}

	/**
	 * Clears out the collVentaCuniaComercials collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addVentaCuniaComercials()
	 */
	public function clearVentaCuniaComercials()
	{
		$this->collVentaCuniaComercials = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collVentaCuniaComercials collection (array).
	 *
	 * By default this just sets the collVentaCuniaComercials collection to an empty array (like clearcollVentaCuniaComercials());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initVentaCuniaComercials()
	{
		$this->collVentaCuniaComercials = array();
	}

	/**
	 * Gets an array of VentaCuniaComercial objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Venta has previously been saved, it will retrieve
	 * related VentaCuniaComercials from storage. If this Venta is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array VentaCuniaComercial[]
	 * @throws     PropelException
	 */
	public function getVentaCuniaComercials($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(VentaPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collVentaCuniaComercials === null) {
			if ($this->isNew()) {
			   $this->collVentaCuniaComercials = array();
			} else {

				$criteria->add(VentaCuniaComercialPeer::VENTA, $this->codigo);

				VentaCuniaComercialPeer::addSelectColumns($criteria);
				$this->collVentaCuniaComercials = VentaCuniaComercialPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(VentaCuniaComercialPeer::VENTA, $this->codigo);

				VentaCuniaComercialPeer::addSelectColumns($criteria);
				if (!isset($this->lastVentaCuniaComercialCriteria) || !$this->lastVentaCuniaComercialCriteria->equals($criteria)) {
					$this->collVentaCuniaComercials = VentaCuniaComercialPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastVentaCuniaComercialCriteria = $criteria;
		return $this->collVentaCuniaComercials;
	}

	/**
	 * Returns the number of related VentaCuniaComercial objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related VentaCuniaComercial objects.
	 * @throws     PropelException
	 */
	public function countVentaCuniaComercials(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(VentaPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collVentaCuniaComercials === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(VentaCuniaComercialPeer::VENTA, $this->codigo);

				$count = VentaCuniaComercialPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(VentaCuniaComercialPeer::VENTA, $this->codigo);

				if (!isset($this->lastVentaCuniaComercialCriteria) || !$this->lastVentaCuniaComercialCriteria->equals($criteria)) {
					$count = VentaCuniaComercialPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collVentaCuniaComercials);
				}
			} else {
				$count = count($this->collVentaCuniaComercials);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a VentaCuniaComercial object to this object
	 * through the VentaCuniaComercial foreign key attribute.
	 *
	 * @param      VentaCuniaComercial $l VentaCuniaComercial
	 * @return     void
	 * @throws     PropelException
	 */
	public function addVentaCuniaComercial(VentaCuniaComercial $l)
	{
		if ($this->collVentaCuniaComercials === null) {
			$this->initVentaCuniaComercials();
		}
		if (!in_array($l, $this->collVentaCuniaComercials, true)) { // only add it if the **same** object is not already associated
			array_push($this->collVentaCuniaComercials, $l);
			$l->setVentaRelatedByVenta($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Venta is new, it will return
	 * an empty collection; or if this Venta has previously
	 * been saved, it will retrieve related VentaCuniaComercials from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Venta.
	 */
	public function getVentaCuniaComercialsJoinCuniaComercialRelatedByCuniaComercial($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(VentaPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collVentaCuniaComercials === null) {
			if ($this->isNew()) {
				$this->collVentaCuniaComercials = array();
			} else {

				$criteria->add(VentaCuniaComercialPeer::VENTA, $this->codigo);

				$this->collVentaCuniaComercials = VentaCuniaComercialPeer::doSelectJoinCuniaComercialRelatedByCuniaComercial($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(VentaCuniaComercialPeer::VENTA, $this->codigo);

			if (!isset($this->lastVentaCuniaComercialCriteria) || !$this->lastVentaCuniaComercialCriteria->equals($criteria)) {
				$this->collVentaCuniaComercials = VentaCuniaComercialPeer::doSelectJoinCuniaComercialRelatedByCuniaComercial($criteria, $con, $join_behavior);
			}
		}
		$this->lastVentaCuniaComercialCriteria = $criteria;

		return $this->collVentaCuniaComercials;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collProgramacionCancions) {
				foreach ((array) $this->collProgramacionCancions as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collVentaCancions) {
				foreach ((array) $this->collVentaCancions as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collVentaCuniaComercials) {
				foreach ((array) $this->collVentaCuniaComercials as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collProgramacionCancions = null;
		$this->collVentaCancions = null;
		$this->collVentaCuniaComercials = null;
			$this->aUsuarioRelatedByUsuario = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseVenta:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseVenta::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseVenta
