<?php

/**
 * Base class that represents a row from the 'cancion' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sat Dec 11 22:56:28 2010
 *
 * @package    lib.model.om
 */
abstract class BaseCancion extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        CancionPeer
	 */
	protected static $peer;

	/**
	 * The value for the codigo field.
	 * @var        int
	 */
	protected $codigo;

	/**
	 * The value for the nombre field.
	 * @var        string
	 */
	protected $nombre;

	/**
	 * The value for the autor field.
	 * @var        string
	 */
	protected $autor;

	/**
	 * The value for the album field.
	 * @var        string
	 */
	protected $album;

	/**
	 * The value for the fecha_de_publicacion field.
	 * @var        string
	 */
	protected $fecha_de_publicacion;

	/**
	 * The value for the duracion field.
	 * @var        string
	 */
	protected $duracion;

	/**
	 * The value for the url field.
	 * @var        string
	 */
	protected $url;

	/**
	 * The value for the habilitada field.
	 * @var        boolean
	 */
	protected $habilitada;

	/**
	 * The value for the precio field.
	 * @var        string
	 */
	protected $precio;

	/**
	 * The value for the ranking field.
	 * @var        int
	 */
	protected $ranking;

	/**
	 * @var        array VentaCancion[] Collection to store aggregation of VentaCancion objects.
	 */
	protected $collVentaCancions;

	/**
	 * @var        Criteria The criteria used to select the current contents of collVentaCancions.
	 */
	private $lastVentaCancionCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'CancionPeer';

	/**
	 * Get the [codigo] column value.
	 * 
	 * @return     int
	 */
	public function getCodigo()
	{
		return $this->codigo;
	}

	/**
	 * Get the [nombre] column value.
	 * 
	 * @return     string
	 */
	public function getNombre()
	{
		return $this->nombre;
	}

	/**
	 * Get the [autor] column value.
	 * 
	 * @return     string
	 */
	public function getAutor()
	{
		return $this->autor;
	}

	/**
	 * Get the [album] column value.
	 * 
	 * @return     string
	 */
	public function getAlbum()
	{
		return $this->album;
	}

	/**
	 * Get the [optionally formatted] temporal [fecha_de_publicacion] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getFechaDePublicacion($format = 'Y-m-d')
	{
		if ($this->fecha_de_publicacion === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->fecha_de_publicacion);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->fecha_de_publicacion, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [duracion] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getDuracion($format = 'H:i:s')
	{
		if ($this->duracion === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->duracion);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->duracion, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [url] column value.
	 * 
	 * @return     string
	 */
	public function getUrl()
	{
		return $this->url;
	}

	/**
	 * Get the [habilitada] column value.
	 * 
	 * @return     boolean
	 */
	public function getHabilitada()
	{
		return $this->habilitada;
	}

	/**
	 * Get the [precio] column value.
	 * 
	 * @return     string
	 */
	public function getPrecio()
	{
		return $this->precio;
	}

	/**
	 * Get the [ranking] column value.
	 * 
	 * @return     int
	 */
	public function getRanking()
	{
		return $this->ranking;
	}

	/**
	 * Set the value of [codigo] column.
	 * 
	 * @param      int $v new value
	 * @return     Cancion The current object (for fluent API support)
	 */
	public function setCodigo($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->codigo !== $v) {
			$this->codigo = $v;
			$this->modifiedColumns[] = CancionPeer::CODIGO;
		}

		return $this;
	} // setCodigo()

	/**
	 * Set the value of [nombre] column.
	 * 
	 * @param      string $v new value
	 * @return     Cancion The current object (for fluent API support)
	 */
	public function setNombre($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->nombre !== $v) {
			$this->nombre = $v;
			$this->modifiedColumns[] = CancionPeer::NOMBRE;
		}

		return $this;
	} // setNombre()

	/**
	 * Set the value of [autor] column.
	 * 
	 * @param      string $v new value
	 * @return     Cancion The current object (for fluent API support)
	 */
	public function setAutor($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->autor !== $v) {
			$this->autor = $v;
			$this->modifiedColumns[] = CancionPeer::AUTOR;
		}

		return $this;
	} // setAutor()

	/**
	 * Set the value of [album] column.
	 * 
	 * @param      string $v new value
	 * @return     Cancion The current object (for fluent API support)
	 */
	public function setAlbum($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->album !== $v) {
			$this->album = $v;
			$this->modifiedColumns[] = CancionPeer::ALBUM;
		}

		return $this;
	} // setAlbum()

	/**
	 * Sets the value of [fecha_de_publicacion] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Cancion The current object (for fluent API support)
	 */
	public function setFechaDePublicacion($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->fecha_de_publicacion !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->fecha_de_publicacion !== null && $tmpDt = new DateTime($this->fecha_de_publicacion)) ? $tmpDt->format('Y-m-d') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->fecha_de_publicacion = ($dt ? $dt->format('Y-m-d') : null);
				$this->modifiedColumns[] = CancionPeer::FECHA_DE_PUBLICACION;
			}
		} // if either are not null

		return $this;
	} // setFechaDePublicacion()

	/**
	 * Sets the value of [duracion] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Cancion The current object (for fluent API support)
	 */
	public function setDuracion($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->duracion !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->duracion !== null && $tmpDt = new DateTime($this->duracion)) ? $tmpDt->format('H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->duracion = ($dt ? $dt->format('H:i:s') : null);
				$this->modifiedColumns[] = CancionPeer::DURACION;
			}
		} // if either are not null

		return $this;
	} // setDuracion()

	/**
	 * Set the value of [url] column.
	 * 
	 * @param      string $v new value
	 * @return     Cancion The current object (for fluent API support)
	 */
	public function setUrl($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->url !== $v) {
			$this->url = $v;
			$this->modifiedColumns[] = CancionPeer::URL;
		}

		return $this;
	} // setUrl()

	/**
	 * Set the value of [habilitada] column.
	 * 
	 * @param      boolean $v new value
	 * @return     Cancion The current object (for fluent API support)
	 */
	public function setHabilitada($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->habilitada !== $v) {
			$this->habilitada = $v;
			$this->modifiedColumns[] = CancionPeer::HABILITADA;
		}

		return $this;
	} // setHabilitada()

	/**
	 * Set the value of [precio] column.
	 * 
	 * @param      string $v new value
	 * @return     Cancion The current object (for fluent API support)
	 */
	public function setPrecio($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->precio !== $v) {
			$this->precio = $v;
			$this->modifiedColumns[] = CancionPeer::PRECIO;
		}

		return $this;
	} // setPrecio()

	/**
	 * Set the value of [ranking] column.
	 * 
	 * @param      int $v new value
	 * @return     Cancion The current object (for fluent API support)
	 */
	public function setRanking($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->ranking !== $v) {
			$this->ranking = $v;
			$this->modifiedColumns[] = CancionPeer::RANKING;
		}

		return $this;
	} // setRanking()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->codigo = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->nombre = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->autor = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->album = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->fecha_de_publicacion = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->duracion = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->url = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->habilitada = ($row[$startcol + 7] !== null) ? (boolean) $row[$startcol + 7] : null;
			$this->precio = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->ranking = ($row[$startcol + 9] !== null) ? (int) $row[$startcol + 9] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 10; // 10 = CancionPeer::NUM_COLUMNS - CancionPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Cancion object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(CancionPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = CancionPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->collVentaCancions = null;
			$this->lastVentaCancionCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(CancionPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseCancion:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				CancionPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseCancion:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(CancionPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseCancion:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseCancion:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				CancionPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			if ($this->isNew() ) {
				$this->modifiedColumns[] = CancionPeer::CODIGO;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = CancionPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setCodigo($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += CancionPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collVentaCancions !== null) {
				foreach ($this->collVentaCancions as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			if (($retval = CancionPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collVentaCancions !== null) {
					foreach ($this->collVentaCancions as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = CancionPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getCodigo();
				break;
			case 1:
				return $this->getNombre();
				break;
			case 2:
				return $this->getAutor();
				break;
			case 3:
				return $this->getAlbum();
				break;
			case 4:
				return $this->getFechaDePublicacion();
				break;
			case 5:
				return $this->getDuracion();
				break;
			case 6:
				return $this->getUrl();
				break;
			case 7:
				return $this->getHabilitada();
				break;
			case 8:
				return $this->getPrecio();
				break;
			case 9:
				return $this->getRanking();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = CancionPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getCodigo(),
			$keys[1] => $this->getNombre(),
			$keys[2] => $this->getAutor(),
			$keys[3] => $this->getAlbum(),
			$keys[4] => $this->getFechaDePublicacion(),
			$keys[5] => $this->getDuracion(),
			$keys[6] => $this->getUrl(),
			$keys[7] => $this->getHabilitada(),
			$keys[8] => $this->getPrecio(),
			$keys[9] => $this->getRanking(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = CancionPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setCodigo($value);
				break;
			case 1:
				$this->setNombre($value);
				break;
			case 2:
				$this->setAutor($value);
				break;
			case 3:
				$this->setAlbum($value);
				break;
			case 4:
				$this->setFechaDePublicacion($value);
				break;
			case 5:
				$this->setDuracion($value);
				break;
			case 6:
				$this->setUrl($value);
				break;
			case 7:
				$this->setHabilitada($value);
				break;
			case 8:
				$this->setPrecio($value);
				break;
			case 9:
				$this->setRanking($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = CancionPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setCodigo($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setNombre($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setAutor($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setAlbum($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setFechaDePublicacion($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setDuracion($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setUrl($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setHabilitada($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setPrecio($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setRanking($arr[$keys[9]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(CancionPeer::DATABASE_NAME);

		if ($this->isColumnModified(CancionPeer::CODIGO)) $criteria->add(CancionPeer::CODIGO, $this->codigo);
		if ($this->isColumnModified(CancionPeer::NOMBRE)) $criteria->add(CancionPeer::NOMBRE, $this->nombre);
		if ($this->isColumnModified(CancionPeer::AUTOR)) $criteria->add(CancionPeer::AUTOR, $this->autor);
		if ($this->isColumnModified(CancionPeer::ALBUM)) $criteria->add(CancionPeer::ALBUM, $this->album);
		if ($this->isColumnModified(CancionPeer::FECHA_DE_PUBLICACION)) $criteria->add(CancionPeer::FECHA_DE_PUBLICACION, $this->fecha_de_publicacion);
		if ($this->isColumnModified(CancionPeer::DURACION)) $criteria->add(CancionPeer::DURACION, $this->duracion);
		if ($this->isColumnModified(CancionPeer::URL)) $criteria->add(CancionPeer::URL, $this->url);
		if ($this->isColumnModified(CancionPeer::HABILITADA)) $criteria->add(CancionPeer::HABILITADA, $this->habilitada);
		if ($this->isColumnModified(CancionPeer::PRECIO)) $criteria->add(CancionPeer::PRECIO, $this->precio);
		if ($this->isColumnModified(CancionPeer::RANKING)) $criteria->add(CancionPeer::RANKING, $this->ranking);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(CancionPeer::DATABASE_NAME);

		$criteria->add(CancionPeer::CODIGO, $this->codigo);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getCodigo();
	}

	/**
	 * Generic method to set the primary key (codigo column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setCodigo($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Cancion (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setNombre($this->nombre);

		$copyObj->setAutor($this->autor);

		$copyObj->setAlbum($this->album);

		$copyObj->setFechaDePublicacion($this->fecha_de_publicacion);

		$copyObj->setDuracion($this->duracion);

		$copyObj->setUrl($this->url);

		$copyObj->setHabilitada($this->habilitada);

		$copyObj->setPrecio($this->precio);

		$copyObj->setRanking($this->ranking);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getVentaCancions() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addVentaCancion($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setCodigo(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Cancion Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     CancionPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new CancionPeer();
		}
		return self::$peer;
	}

	/**
	 * Clears out the collVentaCancions collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addVentaCancions()
	 */
	public function clearVentaCancions()
	{
		$this->collVentaCancions = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collVentaCancions collection (array).
	 *
	 * By default this just sets the collVentaCancions collection to an empty array (like clearcollVentaCancions());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initVentaCancions()
	{
		$this->collVentaCancions = array();
	}

	/**
	 * Gets an array of VentaCancion objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Cancion has previously been saved, it will retrieve
	 * related VentaCancions from storage. If this Cancion is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array VentaCancion[]
	 * @throws     PropelException
	 */
	public function getVentaCancions($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(CancionPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collVentaCancions === null) {
			if ($this->isNew()) {
			   $this->collVentaCancions = array();
			} else {

				$criteria->add(VentaCancionPeer::CANCION, $this->codigo);

				VentaCancionPeer::addSelectColumns($criteria);
				$this->collVentaCancions = VentaCancionPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(VentaCancionPeer::CANCION, $this->codigo);

				VentaCancionPeer::addSelectColumns($criteria);
				if (!isset($this->lastVentaCancionCriteria) || !$this->lastVentaCancionCriteria->equals($criteria)) {
					$this->collVentaCancions = VentaCancionPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastVentaCancionCriteria = $criteria;
		return $this->collVentaCancions;
	}

	/**
	 * Returns the number of related VentaCancion objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related VentaCancion objects.
	 * @throws     PropelException
	 */
	public function countVentaCancions(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(CancionPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collVentaCancions === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(VentaCancionPeer::CANCION, $this->codigo);

				$count = VentaCancionPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(VentaCancionPeer::CANCION, $this->codigo);

				if (!isset($this->lastVentaCancionCriteria) || !$this->lastVentaCancionCriteria->equals($criteria)) {
					$count = VentaCancionPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collVentaCancions);
				}
			} else {
				$count = count($this->collVentaCancions);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a VentaCancion object to this object
	 * through the VentaCancion foreign key attribute.
	 *
	 * @param      VentaCancion $l VentaCancion
	 * @return     void
	 * @throws     PropelException
	 */
	public function addVentaCancion(VentaCancion $l)
	{
		if ($this->collVentaCancions === null) {
			$this->initVentaCancions();
		}
		if (!in_array($l, $this->collVentaCancions, true)) { // only add it if the **same** object is not already associated
			array_push($this->collVentaCancions, $l);
			$l->setCancionRelatedByCancion($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Cancion is new, it will return
	 * an empty collection; or if this Cancion has previously
	 * been saved, it will retrieve related VentaCancions from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Cancion.
	 */
	public function getVentaCancionsJoinVentaRelatedByVenta($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(CancionPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collVentaCancions === null) {
			if ($this->isNew()) {
				$this->collVentaCancions = array();
			} else {

				$criteria->add(VentaCancionPeer::CANCION, $this->codigo);

				$this->collVentaCancions = VentaCancionPeer::doSelectJoinVentaRelatedByVenta($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(VentaCancionPeer::CANCION, $this->codigo);

			if (!isset($this->lastVentaCancionCriteria) || !$this->lastVentaCancionCriteria->equals($criteria)) {
				$this->collVentaCancions = VentaCancionPeer::doSelectJoinVentaRelatedByVenta($criteria, $con, $join_behavior);
			}
		}
		$this->lastVentaCancionCriteria = $criteria;

		return $this->collVentaCancions;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collVentaCancions) {
				foreach ((array) $this->collVentaCancions as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collVentaCancions = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseCancion:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseCancion::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseCancion
