<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2010/12/10 10:44:14
sfConfig::add(array(
  'mod_gestionar_cancion_enabled' => true,
  'mod_gestionar_cancion_view_class' => 'sfPHP',
));
