<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2010/12/07 17:06:50
sfConfig::add(array(
  'mod_gestionar_cancion_enabled' => true,
  'mod_gestionar_cancion_view_class' => 'sfPHP',
));
