<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/11/22 14:19:38

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'PropelPDO',
  'dsn' => 'pgsql: host=localhost;port=5432;dbname=oms;user=oms;password=oms',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
