<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2010/12/10 14:56:10
sfConfig::add(array(
  'mod_comprar_cancion_enabled' => true,
  'mod_comprar_cancion_view_class' => 'sfPHP',
));
