<?php


/**
 * Skeleton subclass for performing query and update operations on the 'cancion' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Mon Nov 22 16:46:12 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class CancionPeer extends BaseCancionPeer {
	
	public static function doSelectMesActual(){
		$ventas_cancion = VentaCancionPeer::doSelectMesActual();
		$canciones = null;
		
		foreach ($ventas_cancion As $venta_cancion)
		{
			$cancion = $venta_cancion->getCancionRelatedByCancion();
			$canciones[] = $cancion;
		}
		
		return $canciones;
	}
	
	public static function doSelectMesActualUsuario( $codigo_usuario ){
		$ventas_cancion = VentaCancionPeer::doSelectMesActualUsuario( $codigo_usuario );
		$canciones = null;
		
		foreach ($ventas_cancion As $venta_cancion)
		{
			$cancion = $venta_cancion->getCancionRelatedByCancion();
			$canciones[] = $cancion;
		}
		
		return $canciones;
	}

} // CancionPeer
