<?php


/**
 * Skeleton subclass for performing query and update operations on the 'cunia_comercial' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Mon Nov 22 16:46:12 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class CuniaComercialPeer extends BaseCuniaComercialPeer {
	
	public static function doSelectMesActualUsuario( $codigo_usuario ){
		$ventas_cunia = VentaCuniaComercialPeer::doSelectMesActualUsuario( $codigo_usuario );
		$cunias = null;
		
		foreach ($ventas_cunia As $venta_cunia)
		{
			$cunia = $venta_cunia->getCuniaComercialRelatedByCuniaComercial();
			$cunias[] = $cunia;
		}
		
		return $cunias;
	}
	
} // CuniaComercialPeer
