<?php


/**
 * Skeleton subclass for representing a row from the 'usuario' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Mon Nov 22 16:46:14 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Usuario extends BaseUsuario{
	
	public function esCliente(){
		return ($this->getPerfil()==UsuarioPeer::getCodigoPerfilCliente());
	}
	
	public function esAdministrador(){
		return ($this->getPerfil()==UsuarioPeer::getCodigoPerfilAdmin());
	}
	
	public function validarContrasena($password)
	{
		return( $this->getContrasena()==$password );
	}
	
	/*
	 * Retorna las canciones compradas en el mes actual
	 * */
	public function getCancionesMes(){
		$canciones = CancionPeer::doSelectMesActualUsuario( $this->getCodigo() );
		return $canciones;
	}
	
	/*
	 * Retorna el numero de canciones compradas en el mes actual
	 * */
	public function getNumeroCancionesMes(){
		$canciones = CancionPeer::doSelectMesActualUsuario( $this->getCodigo() );
		return count($canciones);
	}
	
	/*
	 * Retorna el numero de cunias compradas en el mes actual
	 * */
	public function getNumeroCuniaComercialsMes(){
		$cunias = CuniaComercialPeer::doSelectMesActualUsuario( $this->getCodigo() );
		return count($cunias);
	}
	
	/*
	 * Retorna las cunias compradas en el mes actual
	 * */
	public function getCuniaComercialsMes(){
		$cunias = CuniaComercialPeer::doSelectMesActualUsuario( $this->getCodigo() );
		return $cunias;
	}
	
	public function getFacturaMes(){
		$ventasmes = VentaPeer::doSelectMesActualUsuario( $this->getCodigo() );
		
		$total = 0;
		
		foreach($ventasmes As $venta)
		{
			$total += $venta->getPrecio();
		}
		
		return $total;
	}
	
	public function getFacturaCancionMes(){
		$ventas_cancion = VentaCancionPeer::doSelectMesActualUsuario(  $this->getCodigo() );
		
		$total = 0;
		
		foreach ($ventas_cancion As $venta_cancion)
		{
			$cancion = $venta_cancion->getCancionRelatedByCancion();
			$total += $cancion->getPrecio();
		}
		
		return $total;
	}
	
	public function getFacturaCuniaMes(){
		$ventas_cunia = VentaCuniaComercialPeer::doSelectMesActualUsuario(  $this->getCodigo() );
		
		$total = 0;
		
		foreach ($ventas_cunia As $venta_cunia)
		{
			$cunia = $ventas_cunia->getCuniaComercialRelatedByCuniaComercial();
			$total += $cunia->getPrecio();
		}
		
		return $total;
	}
	
} // Usuario
