<?php


/**
 * Skeleton subclass for performing query and update operations on the 'usuario' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Mon Nov 22 16:46:14 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class UsuarioPeer extends BaseUsuarioPeer {
	
	public static function doCountClientes()
	{
		$criterio = new Criteria();
		$criterio->add(self::PERFIL, self::getCodigoPerfilCliente());
		
		return self::doCount($criterio);
	}
	
	public static function getCodigoPerfilCliente(){
		$c = new Criteria();
		$c->add(PerfilPeer::NOMBRE, 'empresa');
		$perfil = PerfilPeer::doSelectOne($c);
		
		return $perfil->getCodigo();
	}
	
	public static function doCountAdministradores()
	{
		$criterio = new Criteria();
		$criterio->add(self::PERFIL, self::getCodigoPerfilAdmin());
		
		return self::doCount($criterio);
	}
	
	public static function getCodigoPerfilAdmin(){
		$c = new Criteria();
		$c->add(PerfilPeer::NOMBRE, 'admin');
		$perfil = PerfilPeer::doSelectOne($c);
		
		return $perfil->getCodigo();
	}
	
	public static function doSelectOneCliente($login){
		$criterio = new Criteria();
		$criterio->add(self::USUARIO, $login);
		$usuario = self::doSelectOne($criterio);
		
		if($usuario->esCliente())
			return $usuario;
		else
			return null;
	}
	
	public static function doSelectClientes(){
		$criterio = new Criteria();
		$criterio->add(self::PERFIL, self::getCodigoPerfilCliente());
		
		$usuarios = self::doSelect($criterio);
		
		return $usuarios;
	}
	
	public static function doSelectOneAdministrador($login){
		$critero = new Criteria();
		$criterio->add(self::USUARIO, $login);
		$usuario = self::doSelectOne($criterio);
		
		if($usuario->esAdministrador())
			return $usuario;
		else
			return null;
	}
	
	public static function doSelectAdministradores(){
		$criterio = new Criteria();
		$criterio->add(self::PERFIL, self::getCodigoPerfilAdmin());
		
		$usuarios = self::doSelect($criterio);
		
		return $usuarios;
	}

} // UsuarioPeer
