<?php


/**
 * Skeleton subclass for performing query and update operations on the 'venta_cancion' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Mon Nov 22 16:46:14 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class VentaCancionPeer extends BaseVentaCancionPeer {

} // VentaCancionPeer
